#!/bin/bash

. banner 2>/dev/null
. baselib 2>/dev/null

function show_selection
{
	echo -e "\nPlease Select a Task to Execute:\n
[1] View Configuration
[2] Enumerate a Domain
[3] Pingsweep
[4] Portscan
[5] Help Screen
[6] Exit

"	
}

function set_enum_config
{
	show_banner
	echo -e "Your current configuration:
	
[>] Target IP Address: $HOST
[>] Target Ports: 1-$PORT
[>] Target Domain: $DOMAIN

"
	read -p "Do you want to change your configuration?[y/N]: " getopt
	
	case $getopt in
		[yY]|[yY][eE][sS])
			echo null
			;;
		[nN]|[nN][oO])
			clear
			show_menu
			;;
		*)
			set_enum_config
			;;	
	esac
}

function show_help_screen
{
	show_banner
	echo -e " >> HELP SCREEN <<

[*] Configuration Settings

[*] Target IP Address: 

HELP: IP address to be used on port scanning.
      IP address CIDR is also used for ping sweeping.
	
[*] Target Ports:

HELP: Ports specified, start from 1 to set port will be scanned.

[*] Target Domain:

HELP: Targets the website domain, sweeps for subdomains and translates it to targetable IP addresses.
"

	read -p "Main Menu [0] >> " select

	case $select in
		0)
			clear
			show_menu
			;;
		*)
			clear
			show_help_screen
			;;
	esac		
}
