#!/bin/bash

function ch_addr
{
	show_banner
	echo -e "[+] Changing IP Address..\n"
	read -p "[*] Enter New IP address >> " getopt
	
	# Validate and change the last occurence of HOST IP from the config file
	if [[ $getopt =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
		tac $path/config/recon.conf | sed "0,/[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}/s//$getopt/" \
		| tac | tee $path/config/recon.conf
		clear
		set_enum_config
		
	else
		echo -e "\n[-] Incorrect IP Address Format."
		sleep 0.75
		ch_addr
	fi
}

function ch_port
{
	show_banner
	echo -e "[+] Changing Port..\n"
	read -p "[*] Enter a desired end port (2-65535) >> " getopt

	# Validate and change the last occurence of PORT from the config file
	if [[ $getopt =~ ^[0-9]{1,5}$ ]]; then
		tac $path/config/recon.conf | sed "0,/[0-9]\{1,5\}/s//$getopt/" \
		| tac | tee $path/config/recon.conf
		clear
		set_enum_config
	else
		echo -e "\n[-] Incorrect Port Number specified."
		sleep 0.75
		ch_port
	fi
}

function ch_domain
{
	show_banner
	echo -e "[+] Changing Website Domain..\n"
	read -p "[*] Enter a desired domain name: (i.e. cisco.com) >> " getopt

	# Validate and change the last occurence of the domain from the config file
	if [[ $getopt =~ ^([A-Za-z0-9_-])+(\.[A-Za-z]{2,5})+(\.[A-Za-z]{2,5})?$ ]]; then
		tac $path/config/recon.conf | sed -r "0,/([A-Za-z0-9_-])+(\.[A-Za-z]{2,5})+(\.[A-Za-z]{2,5})?/s//$getopt/" \
		| tac | tee $path/config/recon.conf
		clear
		set_enum_config
	else
		echo -e "\n[-] Incorrect Domain specified."
		sleep 0.75
		ch_domain
	fi
}

function host_err
{
	# Check if configuration file has valid hosts.
	HOSTERR=$(grep -oi '^host=\(\.*\).*' $path/config/recon.conf | wc -l)

    if [[ $HOSTERR -eq 0 ]]; then
        echo -e "[-] ERROR: No hosts detected on the configuration file.
"
		read -p ">> " getopt

		case $getopt in
			*)
				exit 0
				;;
		esac
	
	elif [[ $HOSTERR -ge 2 ]]; then
		echo -e "[-] ERROR: Two or more hosts detected on the configuration file.
"	
		read -p ">> " getopt

		case $getopt in
			*)
				exit 0
				;;
		esac
	fi
}

function port_err
{
	# Check if configuration file has valid ports.
	PORTERR=$(grep -oi '^port=\(\.*\).*' $path/config/recon.conf | wc -l)
	
	if [[ $PORTERR -eq 0 ]]; then
		echo -e "[-] ERROR: No end ports detected on the configuration file.
"
		read -p ">> " getopt
	
		case $getopt in
			*)
				exit 0
				;;
		esac

	elif [[ $PORTERR -ge 2 ]]; then
		echo -e "[-] ERROR: Two or more end ports detected on the configuration file.
"
		read -p ">> " getopt

		case $getopt in
			*)
				exit 0
				;;
		esac
	fi
}

function dom_err
{
	# Check if the configuration file has valid domains.
	DOMERR=$(grep -oi '^domain=\(\.*\).*' $path/config/recon.conf | wc -l)

	if [[ $DOMERR -eq 0 ]]; then
		echo -e "[-] ERROR: No web domain detected on the configuration file.
"
		read -p ">> " getopt

		case $getopt in
			*)
				exit 0
				;;
		esac

	elif [[ $DOMERR -ge 2 ]]; then
		echo -e "[-] ERROR: Two or more web domains detected on the configuration file.
"
		read -p ">> " getopt
		
		case $getopt in
			*)
				exit 0
				;;
		esac
	fi
}
